# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

## FOOD TYPES ##
thai = FoodType.create(name: "Thai")
american = FoodType.create(name: "American(New)")
japanese = FoodType.create(name: "Japanese")
vietnamese = FoodType.create(name: "Vietnamese")
mediterranean = FoodType.create(name: "Mediterranean")
burgers = FoodType.create(name: "Burgers")
seafood = FoodType.create(name: "Seafood")
steakhouses = FoodType.create(name: "Steakhouses")
mexican = FoodType.create(name: "Mexican")
italian = FoodType.create(name: "Italian")
pubs = FoodType.create(name: "Pubs")
french = FoodType.create(name: "French")
bakeries = FoodType.create(name: "Bakeries")
pizza = FoodType.create(name: "Pizza")
beer = FoodType.create(name: "Beer")
chinese = FoodType.create(name: "Chinese")
sandwiches = FoodType.create(name: "Sandwiches")
british = FoodType.create(name: "British")
cocktail_bars = FoodType.create(name: "Cocktail Bars")
creperies = FoodType.create(name: "Creperies")
southern = FoodType.create(name: "Southern")
argentine = FoodType.create(name: "Argentine")
hot_dogs = FoodType.create(name: "Hot Dogs")
food_stands = FoodType.create(name: "Food Stands")
grocery = FoodType.create(name: "Grocery")
breakfast_brunch = FoodType.create(name: "Breakfast & Brunch")
middle_eastern = FoodType.create(name: "Middle Eastern")
spanish = FoodType.create(name: "Spanish")
cafes = FoodType.create(name: "Cafes")
sushi_bars = FoodType.create(name: "Sushi Bars")
indian = FoodType.create(name: "Indian")
delis = FoodType.create(name: "Delis")
poke = FoodType.create(name: "Poke")
soup = FoodType.create(name: "Soup")
german = FoodType.create(name: "German")
asian_fusion = FoodType.create(name: "Asian Fusion")
coffee_tea = FoodType.create(name: "Coffee & Tea")
fast_food = FoodType.create(name: "Fast Food")


## RESTAURANTS ##
Restaurant.create(name: "Wild Ginger", address: "1401 3rd Ave", price_range: 2, food_type: thai)
Restaurant.create(name: "Radiator Whiskey", address: "94 Pike St Ste 30", price_range: 2, food_type: american)
Restaurant.create(name: "Japonessa Sushi Cocina", address: "1400 1st Ave", price_range: 2, food_type: japanese)
Restaurant.create(name: "The Triple Door", address: "216 Union St", price_range: 2, food_type: asian_fusion)
Restaurant.create(name: "Ludi's", address: "200 Pike St", price_range: 2, food_type: american)
Restaurant.create(name: "Hot As Pho", address: "1414 2nd Ave", price_range: 1, food_type: vietnamese)
Restaurant.create(name: "RN74", address: "1433 4th Ave", price_range: 3, food_type: american)
Restaurant.create(name: "Gyro Stop Mediterranean Grill", address: "1431 3rd Ave", price_range: 1, food_type: mediterranean)
Restaurant.create(name: "Steak 'n Shake", address: "1417 3rd Ave", price_range: 1, food_type: burgers)
Restaurant.create(name: "Noi Thai Cuisine", address: "1303 1st Ave", price_range: 2, food_type: thai)
Restaurant.create(name: "The Brooklyn Seafood, Steak & Oyster House", address: "1212 2nd Ave", price_range: 3, food_type: seafood)
Restaurant.create(name: "Ben Paris", address: "130 Pike St", price_range: 0, food_type: american)
Restaurant.create(name: "Pike Brewing Company", address: "1415 1st Ave", price_range: 2, food_type: american)
Restaurant.create(name: "Purple Cafe and Wine Bar", address: "1225 4th Ave", price_range: 3, food_type: american)
Restaurant.create(name: "MR SAIGON", address: "215 Pike St", price_range: 0, food_type: vietnamese)
Restaurant.create(name: "Mae Phim Thai", address: "213 Pike St", price_range: 1, food_type: thai)
Restaurant.create(name: "The Capital Grille", address: "1301 4th Ave", price_range: 3, food_type: steakhouses)
Restaurant.create(name: "El Borracho", address: "1521 1st Ave", price_range: 2, food_type: mexican)
Restaurant.create(name: "Matts in the Market", address: "94 Pike St", price_range: 3, food_type: american)
Restaurant.create(name: "Veggie Grill", address: "1427 4th Ave", price_range: 2, food_type: american)
Restaurant.create(name: "Harbor Cafe", address: "1411 4th Ave", price_range: 1, food_type: thai)
Restaurant.create(name: "IL Bistro", address: "93 Pike St", price_range: 3, food_type: italian)
Restaurant.create(name: "Tankard & Tun", address: "1415 1st Ave", price_range: 2, food_type: seafood)
Restaurant.create(name: "Alibi Room", address: "85 Pike St Ste 410", price_range: 2, food_type: american)
Restaurant.create(name: "Blarney Stone Pub & Restaurant", address: "1416 1st Ave", price_range: 1, food_type: pubs)
Restaurant.create(name: "Can Can", address: "94 Pike St", price_range: 2, food_type: french)
Restaurant.create(name: "Harried & Hungry", address: "1415 3rd Ave", price_range: 1, food_type: sandwiches)
Restaurant.create(name: "Piroshky Piroshky", address: "1501 4th Ave Ste 110", price_range: 0, food_type: bakeries)
Restaurant.create(name: "The Diller Room", address: "1224 1st Ave", price_range: 2, food_type: pizza)
Restaurant.create(name: "Yard House", address: "1501 4th Ave", price_range: 2, food_type: american)
Restaurant.create(name: "Place Pigalle", address: "81 Pike St", price_range: 3, food_type: french)
Restaurant.create(name: "DeLaurenti Food & Wine", address: "1435 1st Ave", price_range: 2, food_type: beer)
Restaurant.create(name: "Genghis Khan Restaurant", address: "1422 1st Ave", price_range: 2, food_type: chinese)
Restaurant.create(name: "Sushi Kudasai", address: "925 4th Ave", price_range: 2, food_type: sushi_bars)
Restaurant.create(name: "Pane Pane Sandwiches", address: "304 Union St", price_range: 1, food_type: sandwiches)
Restaurant.create(name: "Goldfinch Tavern", address: "99 Union St", price_range: 3, food_type: seafood)
Restaurant.create(name: "Elephant & Castle", address: "1415 Fifth Ave", price_range: 2, food_type: british)
Restaurant.create(name: "Frolik Kitchen + Cocktails", address: "1415 Fifth Ave", price_range: 2, food_type: american)
Restaurant.create(name: "Maximilien", address: "81A Pike St", price_range: 2, food_type: french)
Restaurant.create(name: "Delicatus", address: "200 University Ave", price_range: 2, food_type: sandwiches)
Restaurant.create(name: "Wild Fish Poke", address: "94 Pike St", price_range: 2, food_type: seafood)
Restaurant.create(name: "Davids & Co", address: "200 University St", price_range: 2, food_type: american)
Restaurant.create(name: "Muse at Benaroya Hall", address: "200 University St", price_range: 3, food_type: american)
Restaurant.create(name: "Fog Room", address: "1610 2nd Ave", price_range: 0, food_type: cocktail_bars)
Restaurant.create(name: "Crepe De France", address: "93 Pike St", price_range: 2, food_type: creperies)
Restaurant.create(name: "Pokeworks", address: "1200 Third Ave", price_range: 2, food_type: poke)
Restaurant.create(name: "Mariscos Mexico", address: "97B Pike St", price_range: 1, food_type: seafood)
Restaurant.create(name: "Palomino", address: "1420 5th Ave", price_range: 2, food_type: american)
Restaurant.create(name: "The Hart and the Hunter", address: "111 Pine St", price_range: 0, food_type: southern)
Restaurant.create(name: "Chipotle Mexican Grill", address: "1501 4th Ave", price_range: 1, food_type: mexican)
Restaurant.create(name: "Patagon", address: "1610 2nd Ave", price_range: 0, food_type: argentine)
Restaurant.create(name: "Pho 25", address: "1525 3rd Ave", price_range: 1, food_type: vietnamese)
Restaurant.create(name: "Daily Dozen Doughnut", address: "93 Pike St", price_range: 1, food_type: bakeries)
Restaurant.create(name: "Dog In The Park", address: "1520 4th Ave", price_range: 1, food_type: hot_dogs)
Restaurant.create(name: "Potbelly Sandwich Shop", address: "1429 4th Ave", price_range: 1, food_type: sandwiches)
Restaurant.create(name: "Chicken Valley", address: "1507 Pike Pl", price_range: 1, food_type: food_stands)
Restaurant.create(name: "La Vaca Burrito Express", address: "1429 1st Ave", price_range: 1, food_type: mexican)
Restaurant.create(name: "The Crumpet Shop", address: "1503 1st Ave", price_range: 1, food_type: bakeries)
Restaurant.create(name: "QDOBA Mexican Eats", address: "217 Pike St", price_range: 1, food_type: mexican)
Restaurant.create(name: "Oriental Mart", address: "1506 Pike Pl", price_range: 1, food_type: grocery)
Restaurant.create(name: "Fonte Coffee - Seattle", address: "1321 1st Ave", price_range: 2, food_type: breakfast_brunch)
Restaurant.create(name: "Sweet Iron Waffles", address: "1200 Third Ave", price_range: 1, food_type: breakfast_brunch)
Restaurant.create(name: "Falafel King", address: "1509 1st Ave", price_range: 1, food_type: middle_eastern)
Restaurant.create(name: "World Fresh Eatery", address: "1218 Third Ave", price_range: 1, food_type: asian_fusion)
Restaurant.create(name: "Hard Rock Cafe", address: "116 Pike Street", price_range: 2, food_type: american)
Restaurant.create(name: "TASTE Cafe", address: "1300 1st Ave", price_range: 2, food_type: american)
Restaurant.create(name: "Pike Place Bar & Grill", address: "90 Pike St Ste 22", price_range: 2, food_type: seafood)
Restaurant.create(name: "Copacabana Cafe", address: "1520 1/2 Pike Pl", price_range: 2, food_type: spanish)
Restaurant.create(name: "Taste of Asia", address: "1501 4th Ave", price_range: 1, food_type: chinese)
Restaurant.create(name: "Chip & Drews", address: "1301 2nd Ave", price_range: 2, food_type: cafes)
Restaurant.create(name: "Ghost Alley Espresso", address: "1499 Post Aly", price_range: 1, food_type: coffee_tea)
Restaurant.create(name: "Umai Sushi and Teriyaki", address: "97 Pike St", price_range: 1, food_type: sushi_bars)
Restaurant.create(name: "Saffron Spice", address: "93 Pike St Ste 3", price_range: 1, food_type: indian)
Restaurant.create(name: "The Original Deli", address: "1215 4th Ave", price_range: 1, food_type: delis)
Restaurant.create(name: "Poke Lover", address: "1307 1st Ave", price_range: 2, food_type: poke)
Restaurant.create(name: "Seattle Bagel Bakery", address: "93 Pike St Ste 4", price_range: 1, food_type: bakeries)
Restaurant.create(name: "Soup's On!", address: "1420 5th Ave", price_range: 1, food_type: soup)
Restaurant.create(name: "Wildfire Taqueria", address: "1420 5th Ave", price_range: 1, food_type: mexican)
Restaurant.create(name: "Fresh Table Cafe", address: "1501 4th Ave", price_range: 1, food_type: sandwiches)
Restaurant.create(name: "Melange Market", address: "1201 3rd Ave Ste 210", price_range: 1, food_type: delis)
Restaurant.create(name: "Bernard's On Seneca", address: "315 Seneca St", price_range: 1, food_type: german)
Restaurant.create(name: "Measure", address: "200 University St", price_range: 3, food_type: american)
Restaurant.create(name: "Unconventional Pizza", address: "800 E Union St", price_range: 2, food_type: pizza)
Restaurant.create(name: "Subway", address: "1414 3rd Ave", price_range: 1, food_type: sandwiches)
Restaurant.create(name: "Specialty's Cafe & Bakery", address: "1400 5th Ave", price_range: 1, food_type: sandwiches)
Restaurant.create(name: "McDonald's", address: "1530 3rd Ave", price_range: 1, food_type: fast_food)
Restaurant.create(name: "Jimmy John's", address: "1200 3rd Ave", price_range: 1, food_type: sandwiches)
